### ISSUE TITLE
__MSG_messagename__ is not parsed in manifest.json

### ISSUE THREAD

**Issue by beaufortfrancois** [MobileChromeApps/mobile-chrome-apps#292] opened 2014-08-25 14:58 UTC
Chrome Desktop Apps have the ability to localize their App Name, Short Name and Description in the manifest file. It would be great to have the same there too.

**Comment by agrieve** [comment] 2015-03-25 01:58
Dupe of #462.

**Closed by agrieve** 2015-03-25 01:58 UTC
Labels: enhancement-for-cca-tool
